// This file is auto-generated by @hey-api/openapi-ts

import { type DefaultError, type InfiniteData, infiniteQueryOptions, queryOptions, type UseMutationOptions } from '@tanstack/react-query';

import { client } from '../client.gen';
import { deleteCasesById, deleteCasesByIdInvitationsByTutorId, deleteDocumentsById, getAuthMe, getCases, getCasesByCaseIdDocuments, getCasesById, getDocumentsByIdDownload, getHealth, getHealthReady, getInvitations, getTutors, getTutorsById, getTutorsByIdDocuments, getTutorsMeProfile, type Options, patchAuthMe, patchCasesById, patchInvitationsById, postAuthLogin, postAuthLogout, postAuthRegister, postCases, postCasesByCaseIdDocuments, postCasesByIdInvitations, postTutorsMeProfileDocuments, putTutorsMeProfile } from '../sdk.gen';
import type { DeleteCasesByIdData, DeleteCasesByIdError, DeleteCasesByIdInvitationsByTutorIdData, DeleteCasesByIdInvitationsByTutorIdError, DeleteCasesByIdInvitationsByTutorIdResponse, DeleteCasesByIdResponse, DeleteDocumentsByIdData, DeleteDocumentsByIdError, DeleteDocumentsByIdResponse, GetAuthMeData, GetAuthMeError, GetAuthMeResponse, GetCasesByCaseIdDocumentsData, GetCasesByCaseIdDocumentsError, GetCasesByCaseIdDocumentsResponse, GetCasesByIdData, GetCasesByIdError, GetCasesByIdResponse, GetCasesData, GetCasesError, GetCasesResponse, GetDocumentsByIdDownloadData, GetDocumentsByIdDownloadError, GetDocumentsByIdDownloadResponse, GetHealthData, GetHealthReadyData, GetHealthReadyError, GetHealthReadyResponse, GetHealthResponse, GetInvitationsData, GetInvitationsError, GetInvitationsResponse, GetTutorsByIdData, GetTutorsByIdDocumentsData, GetTutorsByIdDocumentsError, GetTutorsByIdDocumentsResponse, GetTutorsByIdError, GetTutorsByIdResponse, GetTutorsData, GetTutorsError, GetTutorsMeProfileData, GetTutorsMeProfileError, GetTutorsMeProfileResponse, GetTutorsResponse, PatchAuthMeData, PatchAuthMeError, PatchAuthMeResponse, PatchCasesByIdData, PatchCasesByIdError, PatchCasesByIdResponse, PatchInvitationsByIdData, PatchInvitationsByIdError, PatchInvitationsByIdResponse, PostAuthLoginData, PostAuthLoginError, PostAuthLoginResponse, PostAuthLogoutData, PostAuthLogoutError, PostAuthLogoutResponse, PostAuthRegisterData, PostAuthRegisterError, PostAuthRegisterResponse, PostCasesByCaseIdDocumentsData, PostCasesByCaseIdDocumentsError, PostCasesByCaseIdDocumentsResponse, PostCasesByIdInvitationsData, PostCasesByIdInvitationsError, PostCasesByIdInvitationsResponse, PostCasesData, PostCasesError, PostCasesResponse, PostTutorsMeProfileDocumentsData, PostTutorsMeProfileDocumentsError, PostTutorsMeProfileDocumentsResponse, PutTutorsMeProfileData, PutTutorsMeProfileError, PutTutorsMeProfileResponse } from '../types.gen';

/**
 * Create account
 *
 * Registers a new parent or tutor account. Passwords are hashed server-side. Tutors receive an empty tutor profile initialized with their display name. Returns a JWT on success (same shape as login).
 */
export const postAuthRegisterMutation = (options?: Partial<Options<PostAuthRegisterData>>): UseMutationOptions<PostAuthRegisterResponse, PostAuthRegisterError, Options<PostAuthRegisterData>> => {
    const mutationOptions: UseMutationOptions<PostAuthRegisterResponse, PostAuthRegisterError, Options<PostAuthRegisterData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthRegister({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Log in
 *
 * Authenticates a user with email and password. On success, returns a JWT bearer token along with the user's id, email, and role. Use the token in the Authorize dialog for all protected endpoints.
 */
export const postAuthLoginMutation = (options?: Partial<Options<PostAuthLoginData>>): UseMutationOptions<PostAuthLoginResponse, PostAuthLoginError, Options<PostAuthLoginData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLoginResponse, PostAuthLoginError, Options<PostAuthLoginData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogin({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Log out
 *
 * Stateless — drop the JWT on the client after calling this.
 */
export const postAuthLogoutMutation = (options?: Partial<Options<PostAuthLogoutData>>): UseMutationOptions<PostAuthLogoutResponse, PostAuthLogoutError, Options<PostAuthLogoutData>> => {
    const mutationOptions: UseMutationOptions<PostAuthLogoutResponse, PostAuthLogoutError, Options<PostAuthLogoutData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postAuthLogout({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseUrl' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
        tags?: ReadonlyArray<string>;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean, tags?: ReadonlyArray<string>): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseUrl: options?.baseUrl || (options?.client ?? client).getConfig().baseUrl } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (tags) {
        params.tags = tags;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [params];
};

export const getAuthMeQueryKey = (options?: Options<GetAuthMeData>) => createQueryKey('getAuthMe', options);

/**
 * Get current user
 *
 * Returns the profile of the currently authenticated user, including id, email, role (parent or tutor), and account timestamps. Requires a valid bearer token.
 */
export const getAuthMeOptions = (options?: Options<GetAuthMeData>) => queryOptions<GetAuthMeResponse, GetAuthMeError, GetAuthMeResponse, ReturnType<typeof getAuthMeQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getAuthMe({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getAuthMeQueryKey(options)
});

/**
 * Update current user profile
 *
 * Updates the logged-in user's display name, email, and/or password. Tutors also sync display name to their public tutor profile.
 */
export const patchAuthMeMutation = (options?: Partial<Options<PatchAuthMeData>>): UseMutationOptions<PatchAuthMeResponse, PatchAuthMeError, Options<PatchAuthMeData>> => {
    const mutationOptions: UseMutationOptions<PatchAuthMeResponse, PatchAuthMeError, Options<PatchAuthMeData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchAuthMe({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCasesQueryKey = (options?: Options<GetCasesData>) => createQueryKey('getCases', options);

/**
 * List cases
 *
 * Returns a paginated list of tuition cases. Parents see only cases they created. Tutors see only cases they have been invited to. Query params: `page`, `limit`, `search`, `subject`, `level`, `status`, `skipCount`, and optional `tutorProfileId` (includes `tutorInvitation` for that tutor only). Response includes `meta` with total and totalPages.
 */
export const getCasesOptions = (options?: Options<GetCasesData>) => queryOptions<GetCasesResponse, GetCasesError, GetCasesResponse, ReturnType<typeof getCasesQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCases({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCasesQueryKey(options)
});

const createInfiniteParams = <K extends Pick<QueryKey<Options>[0], 'body' | 'headers' | 'path' | 'query'>>(queryKey: QueryKey<Options>, page: K) => {
    const params = { ...queryKey[0] };
    if (page.body) {
        params.body = {
            ...queryKey[0].body as any,
            ...page.body as any
        };
    }
    if (page.headers) {
        params.headers = {
            ...queryKey[0].headers,
            ...page.headers
        };
    }
    if (page.path) {
        params.path = {
            ...queryKey[0].path as any,
            ...page.path as any
        };
    }
    if (page.query) {
        params.query = {
            ...queryKey[0].query as any,
            ...page.query as any
        };
    }
    return params as unknown as typeof page;
};

export const getCasesInfiniteQueryKey = (options?: Options<GetCasesData>): QueryKey<Options<GetCasesData>> => createQueryKey('getCases', options, true);

/**
 * List cases
 *
 * Returns a paginated list of tuition cases. Parents see only cases they created. Tutors see only cases they have been invited to. Query params: `page`, `limit`, `search`, `subject`, `level`, `status`, `skipCount`, and optional `tutorProfileId` (includes `tutorInvitation` for that tutor only). Response includes `meta` with total and totalPages.
 */
export const getCasesInfiniteOptions = (options?: Options<GetCasesData>) => infiniteQueryOptions<GetCasesResponse, GetCasesError, InfiniteData<GetCasesResponse>, QueryKey<Options<GetCasesData>>, number | Pick<QueryKey<Options<GetCasesData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetCasesData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getCases({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCasesInfiniteQueryKey(options)
});

/**
 * Create new case
 *
 * Creates a new tuition case listing. Only users with the PARENT role can call this endpoint. Required fields are title, subject, level, location, and budget per hour. New cases always start with status open.
 */
export const postCasesMutation = (options?: Partial<Options<PostCasesData>>): UseMutationOptions<PostCasesResponse, PostCasesError, Options<PostCasesData>> => {
    const mutationOptions: UseMutationOptions<PostCasesResponse, PostCasesError, Options<PostCasesData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCases({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Delete case
 *
 * Deletes a tuition case and cascades related invitations and documents. Only the parent who owns the case may call this endpoint. Only open cases can be deleted.
 */
export const deleteCasesByIdMutation = (options?: Partial<Options<DeleteCasesByIdData>>): UseMutationOptions<DeleteCasesByIdResponse, DeleteCasesByIdError, Options<DeleteCasesByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteCasesByIdResponse, DeleteCasesByIdError, Options<DeleteCasesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCasesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCasesByIdQueryKey = (options: Options<GetCasesByIdData>) => createQueryKey('getCasesById', options);

/**
 * Get case
 *
 * Returns full details for a single case, including the list of invited tutors. Parents can view their own cases. Tutors can view cases they are invited to. If the case does not exist or the caller has no access, the API returns 404.
 */
export const getCasesByIdOptions = (options: Options<GetCasesByIdData>) => queryOptions<GetCasesByIdResponse, GetCasesByIdError, GetCasesByIdResponse, ReturnType<typeof getCasesByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCasesById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCasesByIdQueryKey(options)
});

/**
 * Update case
 *
 * Updates an existing tuition case. Only the parent who owns the case may call this endpoint. Send one or more fields to change: title, subject, level, location, budget per hour, or status. At least one field is required.
 */
export const patchCasesByIdMutation = (options?: Partial<Options<PatchCasesByIdData>>): UseMutationOptions<PatchCasesByIdResponse, PatchCasesByIdError, Options<PatchCasesByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchCasesByIdResponse, PatchCasesByIdError, Options<PatchCasesByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchCasesById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Invite tutor
 *
 * Invites a tutor to a tuition case. Only the parent who owns the case may call this endpoint. Provide either tutorId (user id) or tutorProfileId (directory profile id).
 */
export const postCasesByIdInvitationsMutation = (options?: Partial<Options<PostCasesByIdInvitationsData>>): UseMutationOptions<PostCasesByIdInvitationsResponse, PostCasesByIdInvitationsError, Options<PostCasesByIdInvitationsData>> => {
    const mutationOptions: UseMutationOptions<PostCasesByIdInvitationsResponse, PostCasesByIdInvitationsError, Options<PostCasesByIdInvitationsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCasesByIdInvitations({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

/**
 * Revoke invitation
 *
 * Revokes a tutor's invitation to a case. Only the parent who owns the case may call this endpoint. The tutorId path parameter accepts either a tutor user id or tutor profile id.
 */
export const deleteCasesByIdInvitationsByTutorIdMutation = (options?: Partial<Options<DeleteCasesByIdInvitationsByTutorIdData>>): UseMutationOptions<DeleteCasesByIdInvitationsByTutorIdResponse, DeleteCasesByIdInvitationsByTutorIdError, Options<DeleteCasesByIdInvitationsByTutorIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteCasesByIdInvitationsByTutorIdResponse, DeleteCasesByIdInvitationsByTutorIdError, Options<DeleteCasesByIdInvitationsByTutorIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteCasesByIdInvitationsByTutorId({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getCasesByCaseIdDocumentsQueryKey = (options: Options<GetCasesByCaseIdDocumentsData>) => createQueryKey('getCasesByCaseIdDocuments', options);

/**
 * List documents
 *
 * Lists all documents attached to a tuition case. Returns metadata only. To retrieve file bytes, use GET /documents/{id}/download.
 */
export const getCasesByCaseIdDocumentsOptions = (options: Options<GetCasesByCaseIdDocumentsData>) => queryOptions<GetCasesByCaseIdDocumentsResponse, GetCasesByCaseIdDocumentsError, GetCasesByCaseIdDocumentsResponse, ReturnType<typeof getCasesByCaseIdDocumentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getCasesByCaseIdDocuments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getCasesByCaseIdDocumentsQueryKey(options)
});

/**
 * Upload document
 *
 * Uploads a document and attaches it to a tuition case. The file is sent as multipart form data with the field name `file`. Allowed types are PDF, DOCX, PNG, and JPG. Maximum file size is controlled by MAX_FILE_SIZE_MB (default 10 MB). The caller must have access to the case.
 */
export const postCasesByCaseIdDocumentsMutation = (options?: Partial<Options<PostCasesByCaseIdDocumentsData>>): UseMutationOptions<PostCasesByCaseIdDocumentsResponse, PostCasesByCaseIdDocumentsError, Options<PostCasesByCaseIdDocumentsData>> => {
    const mutationOptions: UseMutationOptions<PostCasesByCaseIdDocumentsResponse, PostCasesByCaseIdDocumentsError, Options<PostCasesByCaseIdDocumentsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postCasesByCaseIdDocuments({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getDocumentsByIdDownloadQueryKey = (options: Options<GetDocumentsByIdDownloadData>) => createQueryKey('getDocumentsByIdDownload', options);

/**
 * Download document
 *
 * Downloads a document by id. The server checks that the caller has access before streaming the file bytes.
 */
export const getDocumentsByIdDownloadOptions = (options: Options<GetDocumentsByIdDownloadData>) => queryOptions<GetDocumentsByIdDownloadResponse, GetDocumentsByIdDownloadError, GetDocumentsByIdDownloadResponse, ReturnType<typeof getDocumentsByIdDownloadQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getDocumentsByIdDownload({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getDocumentsByIdDownloadQueryKey(options)
});

/**
 * Delete document
 *
 * Deletes a document. Allowed for the uploader, the case owner, or the profile owner.
 */
export const deleteDocumentsByIdMutation = (options?: Partial<Options<DeleteDocumentsByIdData>>): UseMutationOptions<DeleteDocumentsByIdResponse, DeleteDocumentsByIdError, Options<DeleteDocumentsByIdData>> => {
    const mutationOptions: UseMutationOptions<DeleteDocumentsByIdResponse, DeleteDocumentsByIdError, Options<DeleteDocumentsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await deleteDocumentsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

/**
 * Health check
 *
 * Simple liveness check for monitoring and deployments. Does not require authentication. Returns the service status, current server timestamp, and process uptime in seconds.
 */
export const getHealthOptions = (options?: Options<GetHealthData>) => queryOptions<GetHealthResponse, DefaultError, GetHealthResponse, ReturnType<typeof getHealthQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealth({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthQueryKey(options)
});

export const getHealthReadyQueryKey = (options?: Options<GetHealthReadyData>) => createQueryKey('getHealthReady', options);

/**
 * Readiness check (database)
 *
 * Pings PostgreSQL and returns 200 when the database is reachable. Use for deployment readiness probes and external cron jobs to keep Neon free-tier compute awake (e.g. every 4 minutes).
 */
export const getHealthReadyOptions = (options?: Options<GetHealthReadyData>) => queryOptions<GetHealthReadyResponse, GetHealthReadyError, GetHealthReadyResponse, ReturnType<typeof getHealthReadyQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getHealthReady({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getHealthReadyQueryKey(options)
});

export const getInvitationsQueryKey = (options?: Options<GetInvitationsData>) => createQueryKey('getInvitations', options);

/**
 * List my invitations
 *
 * Returns invitations for the logged-in tutor, each with joined case details. Status `superseded` means another tutor was matched. Query params: `page`, `limit`, `search` (case title), `status` (pending/accepted/declined/superseded).
 */
export const getInvitationsOptions = (options?: Options<GetInvitationsData>) => queryOptions<GetInvitationsResponse, GetInvitationsError, GetInvitationsResponse, ReturnType<typeof getInvitationsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getInvitations({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getInvitationsQueryKey(options)
});

export const getInvitationsInfiniteQueryKey = (options?: Options<GetInvitationsData>): QueryKey<Options<GetInvitationsData>> => createQueryKey('getInvitations', options, true);

/**
 * List my invitations
 *
 * Returns invitations for the logged-in tutor, each with joined case details. Status `superseded` means another tutor was matched. Query params: `page`, `limit`, `search` (case title), `status` (pending/accepted/declined/superseded).
 */
export const getInvitationsInfiniteOptions = (options?: Options<GetInvitationsData>) => infiniteQueryOptions<GetInvitationsResponse, GetInvitationsError, InfiniteData<GetInvitationsResponse>, QueryKey<Options<GetInvitationsData>>, number | Pick<QueryKey<Options<GetInvitationsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetInvitationsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getInvitations({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getInvitationsInfiniteQueryKey(options)
});

/**
 * Accept or decline invitation
 *
 * Accept or decline a pending invitation. Accepting matches the case and supersedes other pending invitations. Returns 409 if the case was already matched, closed, or this invitation is superseded.
 */
export const patchInvitationsByIdMutation = (options?: Partial<Options<PatchInvitationsByIdData>>): UseMutationOptions<PatchInvitationsByIdResponse, PatchInvitationsByIdError, Options<PatchInvitationsByIdData>> => {
    const mutationOptions: UseMutationOptions<PatchInvitationsByIdResponse, PatchInvitationsByIdError, Options<PatchInvitationsByIdData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await patchInvitationsById({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTutorsQueryKey = (options?: Options<GetTutorsData>) => createQueryKey('getTutors', options);

/**
 * List tutors
 *
 * Returns a paginated directory of tutor profiles. Parents only. Query params: `page`, `limit`, `name` and `qualification` (combined with AND, matching the directory UI), or a single `search` across all profile fields (for invite flows). Response includes `meta` with total and totalPages.
 */
export const getTutorsOptions = (options?: Options<GetTutorsData>) => queryOptions<GetTutorsResponse, GetTutorsError, GetTutorsResponse, ReturnType<typeof getTutorsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTutors({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTutorsQueryKey(options)
});

export const getTutorsInfiniteQueryKey = (options?: Options<GetTutorsData>): QueryKey<Options<GetTutorsData>> => createQueryKey('getTutors', options, true);

/**
 * List tutors
 *
 * Returns a paginated directory of tutor profiles. Parents only. Query params: `page`, `limit`, `name` and `qualification` (combined with AND, matching the directory UI), or a single `search` across all profile fields (for invite flows). Response includes `meta` with total and totalPages.
 */
export const getTutorsInfiniteOptions = (options?: Options<GetTutorsData>) => infiniteQueryOptions<GetTutorsResponse, GetTutorsError, InfiniteData<GetTutorsResponse>, QueryKey<Options<GetTutorsData>>, number | Pick<QueryKey<Options<GetTutorsData>>[0], 'body' | 'headers' | 'path' | 'query'>>(
// @ts-ignore
{
    queryFn: async ({ pageParam, queryKey, signal }) => {
        // @ts-ignore
        const page: Pick<QueryKey<Options<GetTutorsData>>[0], 'body' | 'headers' | 'path' | 'query'> = typeof pageParam === 'object' ? pageParam : {
            query: {
                page: pageParam
            }
        };
        const params = createInfiniteParams(queryKey, page);
        const { data } = await getTutors({
            ...options,
            ...params,
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTutorsInfiniteQueryKey(options)
});

export const getTutorsByIdQueryKey = (options: Options<GetTutorsByIdData>) => createQueryKey('getTutorsById', options);

/**
 * Get tutor profile
 *
 * Returns a single tutor's public profile by profile id. Parents may view any profile. Tutors may only view their own profile (use GET /tutors/me/profile for self).
 */
export const getTutorsByIdOptions = (options: Options<GetTutorsByIdData>) => queryOptions<GetTutorsByIdResponse, GetTutorsByIdError, GetTutorsByIdResponse, ReturnType<typeof getTutorsByIdQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTutorsById({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTutorsByIdQueryKey(options)
});

export const getTutorsMeProfileQueryKey = (options?: Options<GetTutorsMeProfileData>) => createQueryKey('getTutorsMeProfile', options);

/**
 * Get my profile
 *
 * Returns the logged-in tutor's own profile. Tutors only. Returns 404 if the tutor has not created a profile yet.
 */
export const getTutorsMeProfileOptions = (options?: Options<GetTutorsMeProfileData>) => queryOptions<GetTutorsMeProfileResponse, GetTutorsMeProfileError, GetTutorsMeProfileResponse, ReturnType<typeof getTutorsMeProfileQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTutorsMeProfile({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTutorsMeProfileQueryKey(options)
});

/**
 * Update my profile
 *
 * Creates or updates the logged-in tutor's profile. Tutors only. Send display name, qualifications, and teaching experiences.
 */
export const putTutorsMeProfileMutation = (options?: Partial<Options<PutTutorsMeProfileData>>): UseMutationOptions<PutTutorsMeProfileResponse, PutTutorsMeProfileError, Options<PutTutorsMeProfileData>> => {
    const mutationOptions: UseMutationOptions<PutTutorsMeProfileResponse, PutTutorsMeProfileError, Options<PutTutorsMeProfileData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await putTutorsMeProfile({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getTutorsByIdDocumentsQueryKey = (options: Options<GetTutorsByIdDocumentsData>) => createQueryKey('getTutorsByIdDocuments', options);

/**
 * List profile documents
 *
 * Lists documents attached to a tutor profile (metadata only). Parents may view any profile's documents. Tutors may only view documents on their own profile.
 */
export const getTutorsByIdDocumentsOptions = (options: Options<GetTutorsByIdDocumentsData>) => queryOptions<GetTutorsByIdDocumentsResponse, GetTutorsByIdDocumentsError, GetTutorsByIdDocumentsResponse, ReturnType<typeof getTutorsByIdDocumentsQueryKey>>({
    queryFn: async ({ queryKey, signal }) => {
        const { data } = await getTutorsByIdDocuments({
            ...options,
            ...queryKey[0],
            signal,
            throwOnError: true
        });
        return data;
    },
    queryKey: getTutorsByIdDocumentsQueryKey(options)
});

/**
 * Upload profile document
 *
 * Uploads a document to the logged-in tutor's profile (e.g. certificates). Tutors only. Allowed types: pdf, docx, png, jpg. Max 10 MB.
 */
export const postTutorsMeProfileDocumentsMutation = (options?: Partial<Options<PostTutorsMeProfileDocumentsData>>): UseMutationOptions<PostTutorsMeProfileDocumentsResponse, PostTutorsMeProfileDocumentsError, Options<PostTutorsMeProfileDocumentsData>> => {
    const mutationOptions: UseMutationOptions<PostTutorsMeProfileDocumentsResponse, PostTutorsMeProfileDocumentsError, Options<PostTutorsMeProfileDocumentsData>> = {
        mutationFn: async (fnOptions) => {
            const { data } = await postTutorsMeProfileDocuments({
                ...options,
                ...fnOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};
