// This file is auto-generated by @hey-api/openapi-ts

import { type Client, type ClientMeta, formDataBodySerializer, type Options as Options2, type RequestResult, type TDataShape } from './client';
import { client } from './client.gen';
import type { DeleteCasesByIdData, DeleteCasesByIdErrors, DeleteCasesByIdInvitationsByTutorIdData, DeleteCasesByIdInvitationsByTutorIdErrors, DeleteCasesByIdInvitationsByTutorIdResponses, DeleteCasesByIdResponses, DeleteDocumentsByIdData, DeleteDocumentsByIdErrors, DeleteDocumentsByIdResponses, GetAuthMeData, GetAuthMeErrors, GetAuthMeResponses, GetCasesByCaseIdDocumentsData, GetCasesByCaseIdDocumentsErrors, GetCasesByCaseIdDocumentsResponses, GetCasesByIdData, GetCasesByIdErrors, GetCasesByIdResponses, GetCasesData, GetCasesErrors, GetCasesResponses, GetDocumentsByIdDownloadData, GetDocumentsByIdDownloadErrors, GetDocumentsByIdDownloadResponses, GetHealthData, GetHealthReadyData, GetHealthReadyErrors, GetHealthReadyResponses, GetHealthResponses, GetInvitationsData, GetInvitationsErrors, GetInvitationsResponses, GetTutorsByIdData, GetTutorsByIdDocumentsData, GetTutorsByIdDocumentsErrors, GetTutorsByIdDocumentsResponses, GetTutorsByIdErrors, GetTutorsByIdResponses, GetTutorsData, GetTutorsErrors, GetTutorsMeProfileData, GetTutorsMeProfileErrors, GetTutorsMeProfileResponses, GetTutorsResponses, PatchAuthMeData, PatchAuthMeErrors, PatchAuthMeResponses, PatchCasesByIdData, PatchCasesByIdErrors, PatchCasesByIdResponses, PatchInvitationsByIdData, PatchInvitationsByIdErrors, PatchInvitationsByIdResponses, PostAuthLoginData, PostAuthLoginErrors, PostAuthLoginResponses, PostAuthLogoutData, PostAuthLogoutErrors, PostAuthLogoutResponses, PostAuthRegisterData, PostAuthRegisterErrors, PostAuthRegisterResponses, PostCasesByCaseIdDocumentsData, PostCasesByCaseIdDocumentsErrors, PostCasesByCaseIdDocumentsResponses, PostCasesByIdInvitationsData, PostCasesByIdInvitationsErrors, PostCasesByIdInvitationsResponses, PostCasesData, PostCasesErrors, PostCasesResponses, PostTutorsMeProfileDocumentsData, PostTutorsMeProfileDocumentsErrors, PostTutorsMeProfileDocumentsResponses, PutTutorsMeProfileData, PutTutorsMeProfileErrors, PutTutorsMeProfileResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Create account
 *
 * Registers a new parent or tutor account. Passwords are hashed server-side. Tutors receive an empty tutor profile initialized with their display name. Returns a JWT on success (same shape as login).
 */
export const postAuthRegister = <ThrowOnError extends boolean = false>(options?: Options<PostAuthRegisterData, ThrowOnError>): RequestResult<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError> => (options?.client ?? client).post<PostAuthRegisterResponses, PostAuthRegisterErrors, ThrowOnError>({
    url: '/auth/register',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Log in
 *
 * Authenticates a user with email and password. On success, returns a JWT bearer token along with the user's id, email, and role. Use the token in the Authorize dialog for all protected endpoints.
 */
export const postAuthLogin = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLoginData, ThrowOnError>): RequestResult<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError> => (options?.client ?? client).post<PostAuthLoginResponses, PostAuthLoginErrors, ThrowOnError>({
    url: '/auth/login',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Log out
 *
 * Stateless — drop the JWT on the client after calling this.
 */
export const postAuthLogout = <ThrowOnError extends boolean = false>(options?: Options<PostAuthLogoutData, ThrowOnError>): RequestResult<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError> => (options?.client ?? client).post<PostAuthLogoutResponses, PostAuthLogoutErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/logout',
    ...options
});

/**
 * Get current user
 *
 * Returns the profile of the currently authenticated user, including id, email, role (parent or tutor), and account timestamps. Requires a valid bearer token.
 */
export const getAuthMe = <ThrowOnError extends boolean = false>(options?: Options<GetAuthMeData, ThrowOnError>): RequestResult<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError> => (options?.client ?? client).get<GetAuthMeResponses, GetAuthMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options
});

/**
 * Update current user profile
 *
 * Updates the logged-in user's display name, email, and/or password. Tutors also sync display name to their public tutor profile.
 */
export const patchAuthMe = <ThrowOnError extends boolean = false>(options?: Options<PatchAuthMeData, ThrowOnError>): RequestResult<PatchAuthMeResponses, PatchAuthMeErrors, ThrowOnError> => (options?.client ?? client).patch<PatchAuthMeResponses, PatchAuthMeErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/auth/me',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * List cases
 *
 * Returns a paginated list of tuition cases. Parents see only cases they created. Tutors see only cases they have been invited to. Query params: `page`, `limit`, `search` (matches title, subject, or location), `subject`, `level`, `status` (open/matched/closed). Response includes `meta` with total and totalPages.
 */
export const getCases = <ThrowOnError extends boolean = false>(options?: Options<GetCasesData, ThrowOnError>): RequestResult<GetCasesResponses, GetCasesErrors, ThrowOnError> => (options?.client ?? client).get<GetCasesResponses, GetCasesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cases',
    ...options
});

/**
 * Create new case
 *
 * Creates a new tuition case listing. Only users with the PARENT role can call this endpoint. Required fields are title, subject, level, location, and budget per hour. New cases always start with status open.
 */
export const postCases = <ThrowOnError extends boolean = false>(options?: Options<PostCasesData, ThrowOnError>): RequestResult<PostCasesResponses, PostCasesErrors, ThrowOnError> => (options?.client ?? client).post<PostCasesResponses, PostCasesErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cases',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * Delete case
 *
 * Deletes a tuition case and cascades related invitations and documents. Only the parent who owns the case may call this endpoint.
 */
export const deleteCasesById = <ThrowOnError extends boolean = false>(options: Options<DeleteCasesByIdData, ThrowOnError>): RequestResult<DeleteCasesByIdResponses, DeleteCasesByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteCasesByIdResponses, DeleteCasesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cases/{id}',
    ...options
});

/**
 * Get case
 *
 * Returns full details for a single case, including the list of invited tutors. Parents can view their own cases. Tutors can view cases they are invited to. If the case does not exist or the caller has no access, the API returns 404.
 */
export const getCasesById = <ThrowOnError extends boolean = false>(options: Options<GetCasesByIdData, ThrowOnError>): RequestResult<GetCasesByIdResponses, GetCasesByIdErrors, ThrowOnError> => (options.client ?? client).get<GetCasesByIdResponses, GetCasesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cases/{id}',
    ...options
});

/**
 * Update case
 *
 * Updates an existing tuition case. Only the parent who owns the case may call this endpoint. Send one or more fields to change: title, subject, level, location, budget per hour, or status. At least one field is required.
 */
export const patchCasesById = <ThrowOnError extends boolean = false>(options: Options<PatchCasesByIdData, ThrowOnError>): RequestResult<PatchCasesByIdResponses, PatchCasesByIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchCasesByIdResponses, PatchCasesByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cases/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Invite tutor
 *
 * Invites a tutor to a tuition case. Only the parent who owns the case may call this endpoint. Provide either tutorId (user id) or tutorProfileId (directory profile id).
 */
export const postCasesByIdInvitations = <ThrowOnError extends boolean = false>(options: Options<PostCasesByIdInvitationsData, ThrowOnError>): RequestResult<PostCasesByIdInvitationsResponses, PostCasesByIdInvitationsErrors, ThrowOnError> => (options.client ?? client).post<PostCasesByIdInvitationsResponses, PostCasesByIdInvitationsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cases/{id}/invitations',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * Revoke invitation
 *
 * Revokes a tutor's invitation to a case. Only the parent who owns the case may call this endpoint. The tutorId path parameter accepts either a tutor user id or tutor profile id.
 */
export const deleteCasesByIdInvitationsByTutorId = <ThrowOnError extends boolean = false>(options: Options<DeleteCasesByIdInvitationsByTutorIdData, ThrowOnError>): RequestResult<DeleteCasesByIdInvitationsByTutorIdResponses, DeleteCasesByIdInvitationsByTutorIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteCasesByIdInvitationsByTutorIdResponses, DeleteCasesByIdInvitationsByTutorIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cases/{id}/invitations/{tutorId}',
    ...options
});

/**
 * List documents
 *
 * Lists all documents attached to a tuition case. Returns metadata only. To retrieve file bytes, use GET /documents/{id}/download.
 */
export const getCasesByCaseIdDocuments = <ThrowOnError extends boolean = false>(options: Options<GetCasesByCaseIdDocumentsData, ThrowOnError>): RequestResult<GetCasesByCaseIdDocumentsResponses, GetCasesByCaseIdDocumentsErrors, ThrowOnError> => (options.client ?? client).get<GetCasesByCaseIdDocumentsResponses, GetCasesByCaseIdDocumentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cases/{caseId}/documents',
    ...options
});

/**
 * Upload document
 *
 * Uploads a document and attaches it to a tuition case. The file is sent as multipart form data with the field name `file`. Allowed types are PDF, DOCX, PNG, and JPG. Maximum file size is controlled by MAX_FILE_SIZE_MB (default 10 MB). The caller must have access to the case.
 */
export const postCasesByCaseIdDocuments = <ThrowOnError extends boolean = false>(options: Options<PostCasesByCaseIdDocumentsData, ThrowOnError>): RequestResult<PostCasesByCaseIdDocumentsResponses, PostCasesByCaseIdDocumentsErrors, ThrowOnError> => (options.client ?? client).post<PostCasesByCaseIdDocumentsResponses, PostCasesByCaseIdDocumentsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/cases/{caseId}/documents',
    ...options,
    headers: {
        'Content-Type': null,
        ...options.headers
    }
});

/**
 * Download document
 *
 * Downloads a document by id. The server checks that the caller has access before streaming the file bytes.
 */
export const getDocumentsByIdDownload = <ThrowOnError extends boolean = false>(options: Options<GetDocumentsByIdDownloadData, ThrowOnError>): RequestResult<GetDocumentsByIdDownloadResponses, GetDocumentsByIdDownloadErrors, ThrowOnError> => (options.client ?? client).get<GetDocumentsByIdDownloadResponses, GetDocumentsByIdDownloadErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/documents/{id}/download',
    ...options
});

/**
 * Delete document
 *
 * Deletes a document. Allowed for the uploader, the case owner, or the profile owner.
 */
export const deleteDocumentsById = <ThrowOnError extends boolean = false>(options: Options<DeleteDocumentsByIdData, ThrowOnError>): RequestResult<DeleteDocumentsByIdResponses, DeleteDocumentsByIdErrors, ThrowOnError> => (options.client ?? client).delete<DeleteDocumentsByIdResponses, DeleteDocumentsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/documents/{id}',
    ...options
});

/**
 * Health check
 *
 * Simple liveness check for monitoring and deployments. Does not require authentication. Returns the service status, current server timestamp, and process uptime in seconds.
 */
export const getHealth = <ThrowOnError extends boolean = false>(options?: Options<GetHealthData, ThrowOnError>): RequestResult<GetHealthResponses, unknown, ThrowOnError> => (options?.client ?? client).get<GetHealthResponses, unknown, ThrowOnError>({ url: '/health', ...options });

/**
 * Readiness check (database)
 *
 * Pings PostgreSQL and returns 200 when the database is reachable. Use for deployment readiness probes and external cron jobs to keep Neon free-tier compute awake (e.g. every 4 minutes).
 */
export const getHealthReady = <ThrowOnError extends boolean = false>(options?: Options<GetHealthReadyData, ThrowOnError>): RequestResult<GetHealthReadyResponses, GetHealthReadyErrors, ThrowOnError> => (options?.client ?? client).get<GetHealthReadyResponses, GetHealthReadyErrors, ThrowOnError>({ url: '/health/ready', ...options });

/**
 * List my invitations
 *
 * Returns invitations for the logged-in tutor, each with joined case details. Status `superseded` means another tutor was matched. Query params: `page`, `limit`, `search` (case title), `status` (pending/accepted/declined/superseded).
 */
export const getInvitations = <ThrowOnError extends boolean = false>(options?: Options<GetInvitationsData, ThrowOnError>): RequestResult<GetInvitationsResponses, GetInvitationsErrors, ThrowOnError> => (options?.client ?? client).get<GetInvitationsResponses, GetInvitationsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/invitations',
    ...options
});

/**
 * Accept or decline invitation
 *
 * Accept or decline a pending invitation. Accepting matches the case and supersedes other pending invitations. Returns 409 if the case was already matched, closed, or this invitation is superseded.
 */
export const patchInvitationsById = <ThrowOnError extends boolean = false>(options: Options<PatchInvitationsByIdData, ThrowOnError>): RequestResult<PatchInvitationsByIdResponses, PatchInvitationsByIdErrors, ThrowOnError> => (options.client ?? client).patch<PatchInvitationsByIdResponses, PatchInvitationsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/invitations/{id}',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options.headers
    }
});

/**
 * List tutors
 *
 * Returns a paginated directory of tutor profiles. Query params: `page`, `limit`, `name` and `qualification` (combined with AND, matching the directory UI), or a single `search` across all profile fields (for invite flows). Response includes `meta` with total and totalPages.
 */
export const getTutors = <ThrowOnError extends boolean = false>(options?: Options<GetTutorsData, ThrowOnError>): RequestResult<GetTutorsResponses, GetTutorsErrors, ThrowOnError> => (options?.client ?? client).get<GetTutorsResponses, GetTutorsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tutors',
    ...options
});

/**
 * Get tutor profile
 *
 * Returns a single tutor's public profile by profile id. Any authenticated user may view profiles in the directory.
 */
export const getTutorsById = <ThrowOnError extends boolean = false>(options: Options<GetTutorsByIdData, ThrowOnError>): RequestResult<GetTutorsByIdResponses, GetTutorsByIdErrors, ThrowOnError> => (options.client ?? client).get<GetTutorsByIdResponses, GetTutorsByIdErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tutors/{id}',
    ...options
});

/**
 * Get my profile
 *
 * Returns the logged-in tutor's own profile. Tutors only. Returns 404 if the tutor has not created a profile yet.
 */
export const getTutorsMeProfile = <ThrowOnError extends boolean = false>(options?: Options<GetTutorsMeProfileData, ThrowOnError>): RequestResult<GetTutorsMeProfileResponses, GetTutorsMeProfileErrors, ThrowOnError> => (options?.client ?? client).get<GetTutorsMeProfileResponses, GetTutorsMeProfileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tutors/me/profile',
    ...options
});

/**
 * Update my profile
 *
 * Creates or updates the logged-in tutor's profile. Tutors only. Send display name, qualifications, and teaching experiences.
 */
export const putTutorsMeProfile = <ThrowOnError extends boolean = false>(options?: Options<PutTutorsMeProfileData, ThrowOnError>): RequestResult<PutTutorsMeProfileResponses, PutTutorsMeProfileErrors, ThrowOnError> => (options?.client ?? client).put<PutTutorsMeProfileResponses, PutTutorsMeProfileErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tutors/me/profile',
    ...options,
    headers: {
        'Content-Type': 'application/json',
        ...options?.headers
    }
});

/**
 * List profile documents
 *
 * Lists documents attached to a tutor profile (metadata only). Any authenticated user may view documents on public profiles.
 */
export const getTutorsByIdDocuments = <ThrowOnError extends boolean = false>(options: Options<GetTutorsByIdDocumentsData, ThrowOnError>): RequestResult<GetTutorsByIdDocumentsResponses, GetTutorsByIdDocumentsErrors, ThrowOnError> => (options.client ?? client).get<GetTutorsByIdDocumentsResponses, GetTutorsByIdDocumentsErrors, ThrowOnError>({
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tutors/{id}/documents',
    ...options
});

/**
 * Upload profile document
 *
 * Uploads a document to the logged-in tutor's profile (e.g. certificates). Tutors only. Allowed types: pdf, docx, png, jpg. Max 10 MB.
 */
export const postTutorsMeProfileDocuments = <ThrowOnError extends boolean = false>(options?: Options<PostTutorsMeProfileDocumentsData, ThrowOnError>): RequestResult<PostTutorsMeProfileDocumentsResponses, PostTutorsMeProfileDocumentsErrors, ThrowOnError> => (options?.client ?? client).post<PostTutorsMeProfileDocumentsResponses, PostTutorsMeProfileDocumentsErrors, ThrowOnError>({
    ...formDataBodySerializer,
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tutors/me/profile/documents',
    ...options,
    headers: {
        'Content-Type': null,
        ...options?.headers
    }
});
