// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:3001/api/v1' | (string & {});
};

export type LoginUser = {
    id: string;
    email: string;
    role: 'parent' | 'tutor';
    displayName: string | null;
};

export type LoginResponse = {
    /**
     * JWT bearer token
     */
    token: string;
    user: LoginUser;
};

export type Error = {
    error: {
        message: string;
        code?: string;
        details?: {
            [key: string]: unknown;
        };
    };
};

export type RegisterRequest = {
    email: string;
    password: string;
    role: 'parent' | 'tutor';
    displayName: string;
};

export type LoginRequest = {
    email: string;
    password: string;
    /**
     * When provided, login fails if the account role does not match.
     */
    role?: 'parent' | 'tutor';
};

export type User = {
    id: string;
    email: string;
    role: 'parent' | 'tutor';
    displayName: string | null;
    createdAt: string | null;
    updatedAt: string | null;
};

export type UpdateMeRequest = {
    displayName?: string;
    password?: string;
    currentPassword?: string;
};

export type Case = {
    id: string;
    title: string;
    subject: string;
    level: string;
    location: string;
    budgetPerHour: number;
    status: 'open' | 'matched' | 'closed';
    ownerId: string;
    ownerName: string;
    invitedTutorIds: Array<string>;
    createdAt: string | null;
    updatedAt: string | null;
};

export type CreateCaseRequest = {
    title: string;
    subject: string;
    level: string;
    location: string;
    budgetPerHour: number;
};

export type CaseListResponse = {
    data: Array<Case>;
    meta: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
    };
};

export type CaseDetail = Case & {
    invitations: Array<{
        id: string;
        caseId?: string;
        tutorUserId: string;
        tutorProfileId: string | null;
        invitedAt: string | null;
        status: 'pending' | 'accepted' | 'declined' | 'superseded';
        statusMessage: string | null;
        tutor?: {
            userId: string;
            profileId: string | null;
            email: string;
            displayName: string | null;
        };
    }>;
};

export type UpdateCaseRequest = {
    title?: string;
    subject?: string;
    level?: string;
    location?: string;
    budgetPerHour?: number;
    status?: 'open' | 'matched' | 'closed';
};

export type InviteTutorRequest = {
    /**
     * Tutor user id (optional if tutorProfileId is provided)
     */
    tutorId?: string;
    /**
     * Tutor profile id from the directory (optional if tutorId is provided)
     */
    tutorProfileId?: string;
};

export type Document = {
    id: string;
    originalName: string;
    mimeType: string;
    sizeBytes: number;
    uploadedById: string;
    uploadedByName: string;
    caseId: string | null;
    profileId: string | null;
    createdAt: string | null;
};

export type DocumentListResponse = {
    data: Array<Document>;
};

export type HealthResponse = {
    status: string;
    timestamp: string;
    /**
     * Server uptime in seconds
     */
    uptime: number;
};

export type HealthReadyResponse = HealthResponse & {
    database: string;
};

export type HealthReadyDegradedResponse = HealthReadyResponse & {
    message?: string;
};

export type InvitationWithCase = {
    id: string;
    caseId: string;
    tutorUserId: string;
    tutorProfileId: string | null;
    invitedAt: string | null;
    status: 'pending' | 'accepted' | 'declined' | 'superseded';
    statusMessage: string | null;
    case: {
        id: string;
        title: string;
        subject: string;
        level: string;
        location: string;
        budgetPerHour: number;
        status: 'open' | 'matched' | 'closed';
        ownerId: string;
        ownerName: string;
        invitedTutorIds: Array<string>;
        createdAt: string | null;
        updatedAt: string | null;
    };
};

export type InvitationListResponse = {
    data: Array<InvitationWithCase>;
    meta: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
    };
};

export type UpdateInvitationRequest = {
    status: 'accepted' | 'declined';
};

export type TutorProfileSummary = {
    id: string;
    tutorId: string;
    displayName: string;
    qualifications: Array<string>;
    experiences: Array<string>;
    teachingBackground: string;
    yearsOfExperience: number;
    subjectsTaught: Array<string>;
};

export type TutorProfileListResponse = {
    data: Array<TutorProfileSummary>;
    meta: {
        page: number;
        limit: number;
        total: number;
        totalPages: number;
    };
};

export type TutorProfile = {
    id: string;
    tutorId: string;
    displayName: string;
    qualifications: Array<string>;
    experiences: Array<string>;
    teachingBackground: string;
    yearsOfExperience: number;
    subjectsTaught: Array<string>;
    createdAt: string | null;
    updatedAt: string | null;
};

export type UpsertTutorProfileRequest = {
    displayName: string;
    qualifications: Array<string>;
    teachingBackground?: string;
    yearsOfExperience?: number | null;
    subjectsTaught?: Array<string>;
    experiences?: Array<string>;
};

export type PostAuthRegisterData = {
    body?: RegisterRequest;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type PostAuthRegisterErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Email already registered
     */
    409: Error;
};

export type PostAuthRegisterError = PostAuthRegisterErrors[keyof PostAuthRegisterErrors];

export type PostAuthRegisterResponses = {
    /**
     * Account created
     */
    201: LoginResponse;
};

export type PostAuthRegisterResponse = PostAuthRegisterResponses[keyof PostAuthRegisterResponses];

export type PostAuthLoginData = {
    body?: LoginRequest;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type PostAuthLoginErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Invalid credentials
     */
    401: Error;
};

export type PostAuthLoginError = PostAuthLoginErrors[keyof PostAuthLoginErrors];

export type PostAuthLoginResponses = {
    /**
     * Login successful
     */
    200: LoginResponse;
};

export type PostAuthLoginResponse = PostAuthLoginResponses[keyof PostAuthLoginResponses];

export type PostAuthLogoutData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type PostAuthLogoutErrors = {
    /**
     * Not authenticated
     */
    401: Error;
};

export type PostAuthLogoutError = PostAuthLogoutErrors[keyof PostAuthLogoutErrors];

export type PostAuthLogoutResponses = {
    /**
     * Logged out
     */
    204: void;
};

export type PostAuthLogoutResponse = PostAuthLogoutResponses[keyof PostAuthLogoutResponses];

export type GetAuthMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type GetAuthMeErrors = {
    /**
     * Not authenticated
     */
    401: Error;
};

export type GetAuthMeError = GetAuthMeErrors[keyof GetAuthMeErrors];

export type GetAuthMeResponses = {
    /**
     * Current user
     */
    200: User;
};

export type GetAuthMeResponse = GetAuthMeResponses[keyof GetAuthMeResponses];

export type PatchAuthMeData = {
    body?: UpdateMeRequest;
    path?: never;
    query?: never;
    url: '/auth/me';
};

export type PatchAuthMeErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Not authenticated or wrong current password
     */
    401: Error;
};

export type PatchAuthMeError = PatchAuthMeErrors[keyof PatchAuthMeErrors];

export type PatchAuthMeResponses = {
    /**
     * Updated user
     */
    200: User;
};

export type PatchAuthMeResponse = PatchAuthMeResponses[keyof PatchAuthMeResponses];

export type GetCasesData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        search?: string;
        subject?: string;
        level?: string;
        status?: 'open' | 'matched' | 'closed';
    };
    url: '/cases';
};

export type GetCasesErrors = {
    /**
     * Not authenticated
     */
    401: Error;
};

export type GetCasesError = GetCasesErrors[keyof GetCasesErrors];

export type GetCasesResponses = {
    /**
     * Paginated case list
     */
    200: CaseListResponse;
};

export type GetCasesResponse = GetCasesResponses[keyof GetCasesResponses];

export type PostCasesData = {
    body?: CreateCaseRequest;
    path?: never;
    query?: never;
    url: '/cases';
};

export type PostCasesErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Parents only
     */
    403: Error;
};

export type PostCasesError = PostCasesErrors[keyof PostCasesErrors];

export type PostCasesResponses = {
    /**
     * Case created
     */
    201: Case;
};

export type PostCasesResponse = PostCasesResponses[keyof PostCasesResponses];

export type DeleteCasesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cases/{id}';
};

export type DeleteCasesByIdErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Not the case owner
     */
    403: Error;
    /**
     * Case not found
     */
    404: Error;
};

export type DeleteCasesByIdError = DeleteCasesByIdErrors[keyof DeleteCasesByIdErrors];

export type DeleteCasesByIdResponses = {
    /**
     * Case deleted
     */
    204: void;
};

export type DeleteCasesByIdResponse = DeleteCasesByIdResponses[keyof DeleteCasesByIdResponses];

export type GetCasesByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/cases/{id}';
};

export type GetCasesByIdErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Case not found
     */
    404: Error;
};

export type GetCasesByIdError = GetCasesByIdErrors[keyof GetCasesByIdErrors];

export type GetCasesByIdResponses = {
    /**
     * Case detail with invitations
     */
    200: CaseDetail;
};

export type GetCasesByIdResponse = GetCasesByIdResponses[keyof GetCasesByIdResponses];

export type PatchCasesByIdData = {
    body?: UpdateCaseRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/cases/{id}';
};

export type PatchCasesByIdErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Not the case owner
     */
    403: Error;
    /**
     * Case not found
     */
    404: Error;
};

export type PatchCasesByIdError = PatchCasesByIdErrors[keyof PatchCasesByIdErrors];

export type PatchCasesByIdResponses = {
    /**
     * Updated case
     */
    200: Case;
};

export type PatchCasesByIdResponse = PatchCasesByIdResponses[keyof PatchCasesByIdResponses];

export type PostCasesByIdInvitationsData = {
    body?: InviteTutorRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/cases/{id}/invitations';
};

export type PostCasesByIdInvitationsErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Not the case owner
     */
    403: Error;
    /**
     * Case or tutor not found
     */
    404: Error;
};

export type PostCasesByIdInvitationsError = PostCasesByIdInvitationsErrors[keyof PostCasesByIdInvitationsErrors];

export type PostCasesByIdInvitationsResponses = {
    /**
     * Invitation created
     */
    201: {
        id: string;
        caseId?: string;
        tutorUserId: string;
        tutorProfileId: string | null;
        invitedAt: string | null;
        status: 'pending' | 'accepted' | 'declined' | 'superseded';
        statusMessage: string | null;
        tutor?: {
            userId: string;
            profileId: string | null;
            email: string;
            displayName: string | null;
        };
    };
};

export type PostCasesByIdInvitationsResponse = PostCasesByIdInvitationsResponses[keyof PostCasesByIdInvitationsResponses];

export type DeleteCasesByIdInvitationsByTutorIdData = {
    body?: never;
    path: {
        id: string;
        tutorId: string;
    };
    query?: never;
    url: '/cases/{id}/invitations/{tutorId}';
};

export type DeleteCasesByIdInvitationsByTutorIdErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Not the case owner
     */
    403: Error;
    /**
     * Case or invitation not found
     */
    404: Error;
};

export type DeleteCasesByIdInvitationsByTutorIdError = DeleteCasesByIdInvitationsByTutorIdErrors[keyof DeleteCasesByIdInvitationsByTutorIdErrors];

export type DeleteCasesByIdInvitationsByTutorIdResponses = {
    /**
     * Invitation revoked
     */
    204: void;
};

export type DeleteCasesByIdInvitationsByTutorIdResponse = DeleteCasesByIdInvitationsByTutorIdResponses[keyof DeleteCasesByIdInvitationsByTutorIdResponses];

export type GetCasesByCaseIdDocumentsData = {
    body?: never;
    path: {
        caseId: string;
    };
    query?: never;
    url: '/cases/{caseId}/documents';
};

export type GetCasesByCaseIdDocumentsErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Case not found
     */
    404: Error;
};

export type GetCasesByCaseIdDocumentsError = GetCasesByCaseIdDocumentsErrors[keyof GetCasesByCaseIdDocumentsErrors];

export type GetCasesByCaseIdDocumentsResponses = {
    /**
     * Document list
     */
    200: DocumentListResponse;
};

export type GetCasesByCaseIdDocumentsResponse = GetCasesByCaseIdDocumentsResponses[keyof GetCasesByCaseIdDocumentsResponses];

export type PostCasesByCaseIdDocumentsData = {
    body?: {
        file: Blob | File;
    };
    path: {
        caseId: string;
    };
    query?: never;
    url: '/cases/{caseId}/documents';
};

export type PostCasesByCaseIdDocumentsErrors = {
    /**
     * Invalid file type or size
     */
    400: Error;
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Case not found
     */
    404: Error;
};

export type PostCasesByCaseIdDocumentsError = PostCasesByCaseIdDocumentsErrors[keyof PostCasesByCaseIdDocumentsErrors];

export type PostCasesByCaseIdDocumentsResponses = {
    /**
     * Document uploaded
     */
    201: Document;
};

export type PostCasesByCaseIdDocumentsResponse = PostCasesByCaseIdDocumentsResponses[keyof PostCasesByCaseIdDocumentsResponses];

export type GetDocumentsByIdDownloadData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}/download';
};

export type GetDocumentsByIdDownloadErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Document not found
     */
    404: Error;
};

export type GetDocumentsByIdDownloadError = GetDocumentsByIdDownloadErrors[keyof GetDocumentsByIdDownloadErrors];

export type GetDocumentsByIdDownloadResponses = {
    /**
     * File download
     */
    200: Blob | File;
};

export type GetDocumentsByIdDownloadResponse = GetDocumentsByIdDownloadResponses[keyof GetDocumentsByIdDownloadResponses];

export type DeleteDocumentsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/documents/{id}';
};

export type DeleteDocumentsByIdErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Forbidden
     */
    403: Error;
    /**
     * Document not found
     */
    404: Error;
};

export type DeleteDocumentsByIdError = DeleteDocumentsByIdErrors[keyof DeleteDocumentsByIdErrors];

export type DeleteDocumentsByIdResponses = {
    /**
     * Document deleted
     */
    204: void;
};

export type DeleteDocumentsByIdResponse = DeleteDocumentsByIdResponses[keyof DeleteDocumentsByIdResponses];

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type GetHealthResponses = {
    /**
     * Service is healthy
     */
    200: HealthResponse;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type GetHealthReadyData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health/ready';
};

export type GetHealthReadyErrors = {
    /**
     * Database temporarily unavailable (Neon waking up)
     */
    503: HealthReadyDegradedResponse;
};

export type GetHealthReadyError = GetHealthReadyErrors[keyof GetHealthReadyErrors];

export type GetHealthReadyResponses = {
    /**
     * API and database are healthy
     */
    200: HealthReadyResponse;
};

export type GetHealthReadyResponse = GetHealthReadyResponses[keyof GetHealthReadyResponses];

export type GetInvitationsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        search?: string;
        status?: 'pending' | 'accepted' | 'declined' | 'superseded';
    };
    url: '/invitations';
};

export type GetInvitationsErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Tutors only
     */
    403: Error;
};

export type GetInvitationsError = GetInvitationsErrors[keyof GetInvitationsErrors];

export type GetInvitationsResponses = {
    /**
     * Paginated invitation list
     */
    200: InvitationListResponse;
};

export type GetInvitationsResponse = GetInvitationsResponses[keyof GetInvitationsResponses];

export type PatchInvitationsByIdData = {
    body?: UpdateInvitationRequest;
    path: {
        id: string;
    };
    query?: never;
    url: '/invitations/{id}';
};

export type PatchInvitationsByIdErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Tutors only
     */
    403: Error;
    /**
     * Invitation not found
     */
    404: Error;
};

export type PatchInvitationsByIdError = PatchInvitationsByIdErrors[keyof PatchInvitationsByIdErrors];

export type PatchInvitationsByIdResponses = {
    /**
     * Updated invitation
     */
    200: InvitationWithCase;
};

export type PatchInvitationsByIdResponse = PatchInvitationsByIdResponses[keyof PatchInvitationsByIdResponses];

export type GetTutorsData = {
    body?: never;
    path?: never;
    query?: {
        page?: number;
        limit?: number;
        /**
         * Single-field search across name, qualifications, experiences, teaching background, and subjects taught (for invite modals).
         */
        search?: string;
        /**
         * Filter by tutor display name (directory search bar).
         */
        name?: string;
        /**
         * Filter by qualification, experience, teaching background, or subject taught (directory search bar).
         */
        qualification?: string;
    };
    url: '/tutors';
};

export type GetTutorsErrors = {
    /**
     * Not authenticated
     */
    401: Error;
};

export type GetTutorsError = GetTutorsErrors[keyof GetTutorsErrors];

export type GetTutorsResponses = {
    /**
     * Paginated tutor list
     */
    200: TutorProfileListResponse;
};

export type GetTutorsResponse = GetTutorsResponses[keyof GetTutorsResponses];

export type GetTutorsByIdData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tutors/{id}';
};

export type GetTutorsByIdErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Profile not found
     */
    404: Error;
};

export type GetTutorsByIdError = GetTutorsByIdErrors[keyof GetTutorsByIdErrors];

export type GetTutorsByIdResponses = {
    /**
     * Tutor profile
     */
    200: TutorProfile;
};

export type GetTutorsByIdResponse = GetTutorsByIdResponses[keyof GetTutorsByIdResponses];

export type GetTutorsMeProfileData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/tutors/me/profile';
};

export type GetTutorsMeProfileErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Tutors only
     */
    403: Error;
    /**
     * Profile not found
     */
    404: Error;
};

export type GetTutorsMeProfileError = GetTutorsMeProfileErrors[keyof GetTutorsMeProfileErrors];

export type GetTutorsMeProfileResponses = {
    /**
     * Own tutor profile
     */
    200: TutorProfile;
};

export type GetTutorsMeProfileResponse = GetTutorsMeProfileResponses[keyof GetTutorsMeProfileResponses];

export type PutTutorsMeProfileData = {
    body?: UpsertTutorProfileRequest;
    path?: never;
    query?: never;
    url: '/tutors/me/profile';
};

export type PutTutorsMeProfileErrors = {
    /**
     * Validation error
     */
    400: Error;
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Tutors only
     */
    403: Error;
};

export type PutTutorsMeProfileError = PutTutorsMeProfileErrors[keyof PutTutorsMeProfileErrors];

export type PutTutorsMeProfileResponses = {
    /**
     * Profile saved
     */
    200: TutorProfile;
};

export type PutTutorsMeProfileResponse = PutTutorsMeProfileResponses[keyof PutTutorsMeProfileResponses];

export type GetTutorsByIdDocumentsData = {
    body?: never;
    path: {
        id: string;
    };
    query?: never;
    url: '/tutors/{id}/documents';
};

export type GetTutorsByIdDocumentsErrors = {
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Profile not found
     */
    404: Error;
};

export type GetTutorsByIdDocumentsError = GetTutorsByIdDocumentsErrors[keyof GetTutorsByIdDocumentsErrors];

export type GetTutorsByIdDocumentsResponses = {
    /**
     * Profile document list
     */
    200: {
        data: Array<Document>;
    };
};

export type GetTutorsByIdDocumentsResponse = GetTutorsByIdDocumentsResponses[keyof GetTutorsByIdDocumentsResponses];

export type PostTutorsMeProfileDocumentsData = {
    body?: {
        file: Blob | File;
    };
    path?: never;
    query?: never;
    url: '/tutors/me/profile/documents';
};

export type PostTutorsMeProfileDocumentsErrors = {
    /**
     * Invalid file or no profile
     */
    400: Error;
    /**
     * Not authenticated
     */
    401: Error;
    /**
     * Tutors only
     */
    403: Error;
    /**
     * Profile not found
     */
    404: Error;
};

export type PostTutorsMeProfileDocumentsError = PostTutorsMeProfileDocumentsErrors[keyof PostTutorsMeProfileDocumentsErrors];

export type PostTutorsMeProfileDocumentsResponses = {
    /**
     * Document uploaded
     */
    201: Document;
};

export type PostTutorsMeProfileDocumentsResponse = PostTutorsMeProfileDocumentsResponses[keyof PostTutorsMeProfileDocumentsResponses];
